# Generated by Django 4.2 on 2023-04-07 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='league',
        ),
        migrations.RemoveField(
            model_name='team',
            name='players',
        ),
        migrations.RemoveField(
            model_name='team',
            name='user',
        ),
        migrations.DeleteModel(
            name='Hockey_User',
        ),
        migrations.DeleteModel(
            name='League',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
