# Generated by Django 4.2 on 2023-04-07 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
        ('league', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Player',
        ),
        migrations.AlterField(
            model_name='team',
            name='players',
            field=models.ManyToManyField(to='players.player'),
        ),
    ]
